### PR TITLE
Add ev3dev-sysinfo tool copyright notice for @WasabiFan

### PR DESCRIPTION
**Pull request by WasabiFan**
And the veil of secrecy has been lifted! With great power comes great responsibility :laughing:

### CODE REVIEW

**Comment by dlech** [comment]
It's like finding out Peter Parker is SpiderMan!

**Comment by WasabiFan** [comment]
Sure, except searching for Spider Man online returns cool and related results while searching for me returns... WAT?

snip_20160124213313

**Comment by dlech** [comment]
OMG, @WasabiFan could be the cure for cancer.

**Comment by rhempel** [comment]
I see what you did there.

**Pull request merged**
